### ISSUE TITLE
Autolevel NPC

### ISSUE THREAD

**Issue by burner1024** [Sduibek/fixtsrc#6]
Waiting whole 8 levels for companions to to achieve their final form is tedious. Especially for Katja, who is pretty low on HP in the first place, but appears late in the game.
I think it would be good if there was an option to have them level up as as soon as player level requirement is reached, similarly to sfall's NPCAutoLevel.

**Comment by Sduibek** [comment]
Thanks for the suggestion/request! I agree.

This is now an option in the most recent test files, so it'll be an option in next release of Fixt as well :)

**Comment by burner1024** [comment]
Thank you!
I did something [similar](https://github.com/BGforgeNet/fo2tweaks#party-level-match) in FO2tweaks, by the way.
