### ISSUE TITLE
Outdated link on project page?

### ISSUE THREAD

**Issue by KevinNovak** [Sduibek/fixtsrc#7]
Hey, just noticed that the link that you have next to your project description just redirects to the nma fallout home page:
http://www.nma-fallout.com/showthread.php?194562

Maybe you could link to here instead?
http://www.nma-fallout.com/resources/fallout-fixt-full-all-fixes-and-mods.8/

**Comment by Sduibek** [comment]
Thanks for pointing this out! Looks like i never updated it since NMA changed their URL formatting a while back.

I've updated it to http://www.nma-fallout.com/threads/194562 👍
